apiVersion: v1
kind: Service
metadata: 
  name: evac-backend
  labels:
    app: evac-backend
spec:
  selector:
    app: evac-backend
  ports: 
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer