apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: sdu-evac-frontend
  name: sdu-evac-frontend
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: evac-frontend
  template:
    metadata:
      labels:
        app: evac-frontend
    spec:
      containers:
      - name: evac-frontend
        image: gcr.io/cloud-project-371713/frontend:latest
        ports: 
        - containerPort: 80