apiVersion: v1
kind: Service
metadata:
  labels: 
    app: evac-frontend
  name: evac-frontend
spec:
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector: 
    app: evac-frontend
  type: LoadBalancer